-- ================================================================
-- works_meta seed：把 settings.js 里的 externalRoutes 导入 DB
-- 跑一次即可，重复跑因为 on conflict (slug) do nothing 不会重复插入
-- ================================================================

insert into public.works_meta
  (slug, name, cover_url, info_html, code_url, link_url, codepen_url, open_url, date, sort_weight, is_published, tags)
values
  ('/external/vue-组件页面装修demo',
   'vue-组件页面装修demo',
   'https://iili.io/C2Bnigt.gif',
   '公司项目中需要实现一个页面装修的功能，结合原有的项目思路 + ai（Trae），重新搭建了一个优化后的页面装修demo。<br>目前包括以下功能：1.<code>拖拽排序</code> 2.<code>添加删除</code> 3.<code>页面发布</code> 4.<code>预览功能</code> 5.<code>组件选择</code> 6.<code>尺寸编辑</code> 7.<code>素材库选择</code>',
   'https://github.com/sunwenxu1997/decoration-demo',
   'https://juejin.cn/post/7629167699948240948',
   null,
   'https://sunwenxu1997.github.io/decoration-demo',
   '2026-05-28', 100, true, '{vue,装修}'),

  ('/external/微信小程序实现陀螺仪卡片景深效果',
   '微信小程序实现陀螺仪卡片景深效果',
   'https://iili.io/FDjuxsV.gif',
   '调研微信官方 <code>wx.onGyroscopeChange</code> 实现陀螺仪卡片景深效果。1.<code>wx.onGyroscopeChange</code> 返回 x,y,z 角速度；2.<code>角速度 × 时间 = 旋转角度</code>；3.<code>旋转角度 × 转换系数 = 位移偏移量</code>。',
   'https://github.com/sunwenxu1997/gyroscope-wx-app/blob/master/utils/GyroToTranslate.js',
   'https://juejin.cn/post/7538671814685818895',
   'https://developers.weixin.qq.com/s/RxZLJpme862B',
   null,
   '2025-08-15', 90, true, '{小程序,陀螺仪}'),

  ('/external/animejs-鼠标跟随赞助爱心',
   'animejs-鼠标跟随赞助爱心',
   'https://iili.io/FND8Vl2.gif',
   '复现 animejs 官网右上角赞助效果，巩固动画知识。',
   'https://github.com/sunwenxu1997/sunwenxu1997.github.io/blob/main/src/views/works/anime/anime-%E8%B7%9F%E9%9A%8F%E5%B0%8F%E7%88%B1%E5%BF%83',
   'https://juejin.cn/post/7529834029219856399',
   'https://codepen.io/sunwenxu1997/pen/azvNBVY',
   null,
   '2025-07-22', 80, true, '{anime,动画}'),

  ('/external/Animejs-draggable导航拖拽切换',
   'Animejs-draggable导航拖拽切换',
   'https://iili.io/3bObz9j.gif',
   '对比 GSAP 与 Animejs，最终选用 Animejs（中文文档 + 完善案例）。',
   'https://github.com/sunwenxu1997/sunwenxu1997.github.io/blob/main/src/views/works/anime/anime-draggable%E6%A0%87%E7%AD%BE%E5%86%85%E5%AE%B9%E5%88%87%E6%8D%A2.vue',
   'https://juejin.cn/post/7508556336540745728',
   'https://codepen.io/sunwenxu1997/pen/azzxeXo',
   null,
   '2025-05-26', 70, true, '{anime,拖拽}'),

  ('/external/css-视图切换',
   'css-视图切换(:has,:not选择器)',
   'https://iili.io/2iko07e.gif',
   '通过 <code>:has</code> 和 <code>:not</code> 选择器配合兄弟选择器 <code>+</code>，实现点击控制之前/之后兄弟标签样式。',
   null,
   'https://juejin.cn/post/7462303598707310603',
   'https://codepen.io/sunwenxu1997/pen/RNbYMOX',
   null,
   '2025-01-22', 60, true, '{css,选择器}'),

  ('/external/gsap-3d圆环交错视图滚动',
   'gsap-3d圆环交错视图滚动',
   'https://iili.io/2iHaHiu.gif',
   '结合 GSAP ScrollTrigger + CSS 3D 旋转实现圆环交错滚动。',
   null,
   'https://juejin.cn/post/7461829417750315062',
   'https://codepen.io/sunwenxu1997/pen/qEWKjge',
   null,
   '2025-01-16', 50, true, '{gsap,3d}'),

  ('/external/css-文本溢出展开收起',
   'css-文本溢出展开收起',
   'https://iili.io/24xceTB.gif',
   '通过 <code>-webkit-line-clamp</code> 或 <code>max-height</code> + checkbox 实现展开收起。',
   null,
   'https://juejin.cn/post/6963904955262435336',
   'https://codepen.io/sunwenxu1997/pen/emOGXqR',
   null,
   '2025-01-12', 40, true, '{css}'),

  ('/external/radial-gradient按钮周围边框高亮',
   'radial-gradient按钮周围边框高亮',
   'https://iili.io/2aGRUHx.gif',
   '<code>radial-gradient(100px at {x}px {y}px, ...)</code> 监听鼠标位置实现按钮边框跟随高亮。',
   null,
   'https://juejin.cn/post/7358622889681551372',
   'https://codepen.io/sunwenxu1997/pen/azoopBo',
   null,
   '2024-11-25', 30, true, '{css,渐变}'),

  ('/external/css-电梯导航栏',
   'css-电梯导航栏',
   'https://iili.io/dP08thN.gif',
   '使用 CSS <code>timeline-scope</code> 实现电梯导航高亮（兼容性有限）。',
   null,
   'https://juejin.cn/post/7396342567867301927',
   'https://codepen.io/sunwenxu1997/pen/zYVgZeB',
   null,
   '2024-09-19', 20, true, '{css,scroll}'),

  ('/external/css-鼠标经过卡片时波纹效果',
   'css-鼠标经过卡片时波纹效果',
   'https://iili.io/dgS5isj.gif',
   '使用 CSS <code>:has()</code> 伪类实现鼠标悬停时相邻兄弟标签样式变化。',
   null,
   null,
   'https://codepen.io/HighFlyer/pen/GRLZYKw',
   null,
   '2024-09-13', 10, true, '{css,选择器}'),

  ('/external/svg-filter镂空文字',
   'svg-filter镂空文字',
   'https://iili.io/Ja4B6HN.png',
   '通过 SVG <code>feColorMatrix</code> 滤镜过滤黑色像素实现镂空文字效果。',
   null,
   'https://developer.mozilla.org/zh-CN/docs/Web/SVG/Element/feColorMatrix',
   'https://codepen.io/sunwenxu1997/pen/abMWxKm',
   null,
   '2024-01-23', 0, true, '{svg,滤镜}'),

  ('/external/svg-path路径过渡',
   'svg-path路径过渡',
   'https://iili.io/Ja4qjQs.gif',
   null,
   null,
   null,
   'https://codepen.io/codegridweb/pen/VwEzbqa',
   null,
   null, 0, true, '{svg}'),

  ('/external/gsap-stagger交错动画',
   'gsap-stagger交错动画',
   'https://iili.io/JampcRR.gif',
   '使用 GSAP <code>stagger</code> 实现交错动画，支持 amount/each/yoyo/from 等配置。',
   null,
   'https://gsap.com/resources/getting-started/Staggers',
   'https://codepen.io/sunwenxu1997/pen/eYXGYwr',
   null,
   '2024-01-24', 0, true, '{gsap}'),

  ('/external/mix-blend-mode混合模式-重复文字背景',
   'mix-blend-mode混合模式-重复文字背景',
   'https://iili.io/Jc3Kant.png',
   '通过 <code>mix-blend-mode: screen</code> 或 background-clip 实现文字背景效果。',
   null,
   'https://juejin.cn/post/6844903477429141517',
   'https://codepen.io/sunwenxu1997/pen/vYPeeqa',
   null,
   '2024-01-25', 0, true, '{css,混合模式}'),

  ('/external/radial-gradient圆角裁边入场券',
   'radial-gradient圆角裁边入场券',
   'https://iili.io/djbneHP.png',
   '使用 <code>radial-gradient</code> + <code>background-size: 100% 51%</code> 实现入场券镂空裁边。',
   null,
   'https://codepen.io/cbolson/pen/JjVVPPP',
   'https://codepen.io/sunwenxu1997/pen/bGPjMdK',
   null,
   '2024-08-29', 0, true, '{css,渐变}'),

  ('/external/卡片3D旋转跟随效果',
   '卡片3D旋转跟随效果',
   'https://iili.io/dvlGSqX.gif',
   '根据鼠标位置计算 <code>rotateX/rotateY</code> + <code>transform-style: preserve-3d</code> 实现 3D 跟随。',
   null,
   'https://github.com/chokcoco/iCSS/issues/179',
   'https://codepen.io/sunwenxu1997/pen/PorXbzO',
   null,
   '2024-09-06', 0, true, '{css,3d}'),

  ('/external/3D模型鼠标跟随旋转效果',
   '3D模型鼠标跟随旋转效果',
   'https://iili.io/dSWocdJ.gif',
   '使用 Three.js <code>OBJLoader</code> 加载外部模型 + 鼠标跟随旋转。',
   null,
   null,
   'https://codepen.io/sunwenxu1997/pen/dyBaOEW',
   null,
   '2024-09-09', 0, true, '{three,3d}')
on conflict (slug) do nothing;

-- 验证：看插入结果
select slug, name, date, sort_weight, array_length(tags, 1) as tag_count
from public.works_meta
order by sort_weight desc, date desc nulls last;
